name = "All The Horrors"
author = "emmaexe"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bde800682d6e2bd916ec1382d976c619f6fc973f71df81fc65974faec8a397c1"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"

[options]
acceptable-game-versions = []
